/*
 * Copyright (c) 2014 All Rights Reserved.
 */


package com.taotaosou.main.dao.impl;

import com.taotaosou.foundation.base.data.BaseDao1;

import com.taotaosou.main.dao.InducfResourceArticleDao;
import org.springframework.stereotype.Repository;
import com.taotaosou.main.model.InducfResourceArticleDto;


/**
 * An ibatis based implementation of dao interface <tt>com.taotaosou.main.dao.InducfResourceArticleDao</tt>.
 *
 * This file is generated by <tt>ibatis-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>ibatis</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/inducf_resource_article.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>ibatis-dalgen</tt> 
 * to generate this file.
 *
 * @author dalgen
 */
@Repository("InducfResourceArticleDao")
public class InducfResourceArticleDaoImpl extends BaseDao1 implements InducfResourceArticleDao {

	private static final String namespace="InducfResourceArticle.";

	/**
	 *  Query DB table <tt>inducf_resource_article</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from inducf_resource_article where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return InducfResourceArticleDto
	 *	@throws DataAccessException
	 */	 
    public InducfResourceArticleDto selectById(Integer id) {


        return (InducfResourceArticleDto) super.object(namespace+"INDUCF-RESOURCE-ARTICLE-SELECT-BY-ID", id);

    }

}